name: Python CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black autopep8 ruff
    - name: Check code style with black
      run: black --check .
    - name: Check code style with autopep8
      run: autopep8 --diff --exit-code --recursive .
    - name: Check code with ruff
      run: ruff .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: pytest

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deploy to Production
      run: echo "Deploying application..." # Replace with actual deployment commands